### PR TITLE
Exclude unnecessary files from the npm package

### PR DESCRIPTION
**Pull request by pkuczynski**
Listed a few files and folders which are currently included in the published npm package, while they should not be.

### CODE REVIEW

**Comment by pkuczynski** [comment]
@wesleytodd any feedback?

**Comment by wesleytodd** [comment]
Can you elaborate on why they should not be?  Some people use the tests in shipped packages, and since this is a single very small file, I don't see a point in excluding it.  Is this helpful to you in some way?

**Comment by pkuczynski** [comment]
Same way as java or ruby libraries do not ship tests, I think node packages should not ship them too. They only create unnecessary traffic both when installed from npm, and later when distributed as a serverless function or in a docker container. Especially in serverless cases, some providers have a limit on size...

I agree it's a small file, yet a node app usually depends on few hundred packages (for example app I am working on depends on 721 packages) and if every package would ship with tests and build configuration, this would mean quite a heavy overhead. Hence I am trying to fire up PR to some popular packages and convince their authors to exclude things that are not needed to use their packages :)

**Comment by wesleytodd** [comment]
So my take on this is that, within reason, tarball size is not your build time bottleneck.  This very small package is not the right target for your effort, go after something with more impact.  I am not going to add complexity here for this.  There are some applicable npm rfc's which aim to solve this, I would redirect you to [npm/rfcs](https://github.com/npm/rfcs) to fix this at the root.

**Comment by pkuczynski** [comment]
Fair enough, your call, although I find it hard to understand why you consider this a complexity? It's not very different from `.gitignore` which you already use...

**Comment by wesleytodd** [comment]
> It's not very different from .gitignore which you already use...

Git ignore is a requirement to avoid the complexity of committing `node_modules`. Npm ignore is unnecessary (in the strict sense, like not *required*) and in this case adds very little value to either maintainers or end users.

**Comment by pkuczynski** [comment]
Not really. Both prevent pushing unnecessary files to `git` or `npm`. So in that sense, they both prevent the same thing. Just without `gitignore` you can still skip committing `node_modules`, by not staging them. This is not achievable with `npm`, right?

**Comment by wesleytodd** [comment]
Valid point. This is really a minor point so I am not giong to spend more time on it. I don't mean to be dismissive, but I have other more important things to work than to continue to discuss this point. I don't mean to diminish your point, just have to prioritize my time.

**Pull request closed without merging**
